//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalIntranetBot.UnitTests.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PersonalIntranetBot.UnitTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;Demo&quot;: {
        ///    &quot;_type&quot;: &quot;SearchResponse&quot;,
        ///    &quot;webPages&quot;: {
        ///      &quot;webSearchUrl&quot;: &quot;https://www.bing.com/search?q=jonny+depp+sbb+linkedin&quot;,
        ///      &quot;totalEstimatedMatches&quot;: 586000,
        ///      &quot;value&quot;: [
        ///        {
        ///          &quot;id&quot;: &quot;https://api.cognitive.microsoft.com/api/v7/#WebPages.0&quot;,
        ///          &quot;deepLinks&quot;: null,
        ///          &quot;dateLastCrawled&quot;: &quot;2018-10-28T23:46:00Z&quot;,
        ///          &quot;about&quot;: null,
        ///          &quot;name&quot;: &quot;Johnny Depp’s Jack Sparrow axed from next Pirates of the ...&quot;,
        ///          &quot;url&quot;: &quot;https://to [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string BingSearchResulNoLinkedInProfilesFound {
            get {
                return ResourceManager.GetString("BingSearchResulNoLinkedInProfilesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;Demo&quot;: {
        ///    &quot;_type&quot;: &quot;SearchResponse&quot;,
        ///    &quot;webPages&quot;: {
        ///      &quot;webSearchUrl&quot;: &quot;https://www.bing.com/search?q=kevin+suter+zuara+ag+linkedin&quot;,
        ///      &quot;totalEstimatedMatches&quot;: 21200,
        ///      &quot;value&quot;: [
        ///        {
        ///          &quot;id&quot;: &quot;https://api.cognitive.microsoft.com/api/v7/#WebPages.0&quot;,
        ///          &quot;deepLinks&quot;: null,
        ///          &quot;dateLastCrawled&quot;: &quot;2018-10-31T15:07:00Z&quot;,
        ///          &quot;about&quot;: [
        ///            {
        ///              &quot;name&quot;: null
        ///            },
        ///            {
        ///              &quot;name&quot;: null
        ///         [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string BingSearchResultNameAndCompanyMatchingProfileFound {
            get {
                return ResourceManager.GetString("BingSearchResultNameAndCompanyMatchingProfileFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;Demo&quot;: {
        ///    &quot;_type&quot;: &quot;SearchResponse&quot;,
        ///    &quot;webPages&quot;: {
        ///      &quot;webSearchUrl&quot;: &quot;https://www.bing.com/search?q=till+jakob+isolutions+linkedin&quot;,
        ///      &quot;totalEstimatedMatches&quot;: 75800,
        ///      &quot;value&quot;: [
        ///        {
        ///          &quot;id&quot;: &quot;https://api.cognitive.microsoft.com/api/v7/#WebPages.0&quot;,
        ///          &quot;deepLinks&quot;: null,
        ///          &quot;dateLastCrawled&quot;: &quot;2018-09-16T19:56:00Z&quot;,
        ///          &quot;about&quot;: null,
        ///          &quot;name&quot;: &quot;Till Jakob - Senior Software Developer - ahead | LinkedIn&quot;,
        ///          &quot;url&quot;: &quot;https:/ [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string BingSearchResultNameMatchingProfileFound {
            get {
                return ResourceManager.GetString("BingSearchResultNameMatchingProfileFound", resourceCulture);
            }
        }
    }
}
